config/routes.rb
Rails.application.routes.draw do
  get 'reviews/create'
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:create]
  end
  resources :doses, only: [:destroy]
  resources :review, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_many :reviews
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :find_cocktail, only: [ :show, :edit, :update, :destroy]
  def index
    if params[:query].present?
      @cocktails = Cocktail.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @cocktails = Cocktail.all
    end
  end


  def show
    # @cocktail = Cocktail.find(params[:id])
    @doses = Dose.where(cocktail: @cocktail)
    @dose = Dose.new
    @review = Review.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    @cocktail.update(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    # @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create

    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail), notice: 'Ingredients was successfully created.'
    else
      @review = Review.new
      render "doses/new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review = Review.new(review_params)
    @review.cocktail = @cocktail
    if @review.save
      redirect_to cocktail_path(@cocktail)
    else
      @dose = Dose.new
      render "cocktails/show"
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to cocktail_path(@review.cocktail)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <div class="field">
    <%= f.input :name,  class: "rounded",placeholder: "Mojito", label: false %>
  </div>
  <div class="field">
    <%= f.input :photo, as: :file %>
  </div>
  <div class="field">
   <%= f.submit "Create", class: "dose-btn" %>
   <%= link_to "CANCEL", cocktails_path, class: "back-btn" %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<div class="banner">
  <h1>Create your own cocktail recipe</h1>

  <!-- Typed.js -->
  <!-- <h1>
    <span id="banner-typed-text"></span>
  </h1> -->

  <%= link_to "Add Cocktail", new_cocktail_path, class:"button" %>
</div>

<div class="container mt-5">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <!-- <div class="col-12 col-md-6 col-lg-3"> -->
        <% if cocktail.photo.attached? %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
           url('<%= cl_image_path cocktail.photo.key, height: 200, width: 300, crop: :fill %>');">
            <%= link_to "", cocktail_path(cocktail), class: 'card-link' %>
            <div class="card-description">
              <h2><%= cocktail.name.capitalize %></h2>

            </div>
          </div>
        <% else %>
          <!-- <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://images.unsplash.com/photo-1596097092650-730ba9475ad5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80');"> -->
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path 'cocktail.jpg', height: 200, width: 300, crop: :fill %>');">
            <div class="card-description">
              <h2><%= cocktail.name.capitalize %></h2>
            </div>
            <%= link_to "", cocktail_path(cocktail), class: 'card-link' %>
          </div>
        <% end %>
      <!-- </div> -->
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="form">
  <%= link_to "🔙", cocktails_path, class: "back-btn" %>
  <div class="form-box">
    <div class="subtitle">Create a Cocktail</div>
      <%= simple_form_for @cocktail do |f| %>
        <div class="field">
          <%= f.input :name,  class: "rounded",placeholder: "Mojito", label: false %>
        </div>
        <div class="field">
          <%= f.input :photo, as: :file %>
        </div>
        <div class="field">
         <%= f.submit "Create", class: "dose-btn" %>
        </div>
      <% end %>
    </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner-show">
  <% if @cocktail.photo.attached? %>
    <%= cl_image_tag @cocktail.photo.key, class: "sh-photo" %>
  <% else %>
    <div class="sh-photo" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= image_path 'cocktail.jpg', height: 200, width: 300, crop: :fill %>');">
  <% end %>
  <div class="title"><%= @cocktail.name.upcase %></div>
</div>

<!-- <div class="show-content"> -->

  <!-- INGREDIENT -->
  <div class="ingredient-box">
  <p class="subtitle">Ingredients</p>
  <% if @cocktail.doses.empty? %>
    <p>What's the ingredients for <strong><%= @cocktail.name.upcase %></strong></p>
  <% else %>
    <% @cocktail.doses.each do |dose| %>
      <div>
        <%= dose.ingredient.name %>  -  <%= dose.description %>
        <%= link_to "✖️", dose_path(dose), method: :delete, data: {confirm: "Are you sure?"} %>
      </div>
    <% end %>
  <% end %>
  <div class="mt-5">
    <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
  </div>
</div>

<!-- REVIEW -->
<div class="ingredient-box">
  <p class="subtitle">Reviews</p>
  <% if @cocktail.reviews.empty? %>
    <p>Be the first to let a review</p>
  <% else %>
    <% @cocktail.reviews.each do |review| %>
          <%= review.content %> -
          <% counter = 0 %>
          <% 5.times do %>
            <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
            <% counter += 1 %>
          <% end %>
         - <%= link_to "🗑", review_path(review), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  <% end %>
  <br>
  <br>
  <%= render "reviews/new", cocktail: @cocktail, review: @review %>
</div>

<br>

<!-- </div> -->


<div class="ingredient-box">
  <div class="remove">
    <%= link_to "BACK", cocktails_path, class: "dose-btn" %>
    <!-- <br> -->
    <%#= link_to "EDIT COCKTAIL", edit_cocktail_path(@cocktail), class: "remove", method: :delete, data: { confirm: "Are you sure?" } %>
    <!-- <br> -->
    <%#= link_to "REMOVE COCKTAIL", cocktail_path(@cocktail), class: "remove", method: :delete, data: { confirm: "Are you sure?" } %>
    <!-- <br> -->
  </div>
</div>

app/views/doses/_form.html.erb
<div class="subtitle">Add ingredients here</div>
  <%= simple_form_for ([@cocktail, @dose]) do |f| %>
    <%= f.input :description, placeholder: "Amount", label: false %>
    <%= f.association :ingredient, label: false, include_blank: "Select ingredient", input_html: {class: 'select2'}, include_hidden: false %>
    <%= f.submit "Add", class: "dose-btn" %>
  <% end %>

app/views/doses/_new.html.erb
<div class="subtitle">Add ingredients here</div>
  <%= simple_form_for [cocktail, dose] do |f| %>
    <%= f.input :description, placeholder: "Amount", label: false %>
    <%= f.association :ingredient, label: false, include_blank: "Select ingredient", input_html: {class: 'select2'}, include_hidden: false %>
    <%= f.submit "Add Ingredients", class: "dose-btn" %>
  <% end %>

app/views/doses/new.html.erb
<div class="subtitle">Add ingredients here</div>
  <%= simple_form_for [cocktail, dose] do |f| %>
    <%= f.input :description, placeholder: "Amount", label: false %>
    <%= f.association :ingredient, label: false, include_blank: "Select ingredient", input_html: {class: 'select2'}, include_hidden: false %>
    <%= f.submit "Add", class: "dose-btn" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload', defer: true%> <!-- from app/javascript/packs/application.js -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %> <!-- from app/assets/javascripts/application.js -->
    <%= favicon_link_tag asset_path('drink.png') %>


  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>

    <%#= javascript_include_tag "application" %>
  </body>
</html>

app/views/reviews/_new.html.erb
<div class="subtitle">Add reviews here</div>
<%= simple_form_for [cocktail, review] do |f| %>
  <%= f.input :content, placeholder: "What do you think about the cocktail?", label: false  %>
  <%= f.input :rating, collection: 0..5, label: false, include_blank: "Rating", input_html: {class: 'select2'}, include_hidden: false %>
  <%= f.submit "Add Review", class: "dose-btn" %>
<% end %>

app/views/shared/_cocktail_form.html.erb
<div class="container">
<h1>Cocktail Form</h1>

<%= simple_form_for @cocktail do |f| %>

  <div class="field">
  <%= f.input :name,  class: "rounded" %>
  </div>

  <div class="field">
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form">
  <%= f.submit "Create Cocktail", class: "dose-btn" %>
  </div>

<% end %>
</div>

app/views/shared/_doses_form.html.erb
<div class="subtitle">Add ingredients here</div>
  <%= simple_form_for ([@cocktail, @dose]) do |f| %>
    <%= f.association :ingredient, label: false, include_blank: "Select ingredient", class: "select2", include_hidden: false %>
    <%= f.input :description, placeholder: "Amount", label: false %>
    <%= f.submit "Add", class: "dose-btn" %>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <a class="navbar-brand" href="/">
    <%= image_tag "drink.png" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <%= form_tag cocktails_path, method: :get do %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a cocktails 🍹"
          %>
        </li>
        <li class="nav-item">
          <%= submit_tag "Search", class: "btn btn-primary" %>
        </li>
      </ul>
    <% end %>
  </div>
</div>